export const initialTasks = [
  { title: "Task 1: Setup Project", status: "1" },
  {
    title: "Dehradun Palace Sauna",
    status: "2",
    cost: 4000,
    duration: 2,
    note: "Purchase towels",
    startTime: "23:03",
    endTime: "23:03",
  },
  {
    title: "Task 2: Create Components",
    status: "1",
    cost: 4000,
    duration: 2,
    endTime: "23:03",
    note: "Hello",
    startTime: "23:03",
  },
  {
    title: "Reserve Hotels in Reykjavik",
    status: "2",
    cost: 2000,
    duration: 1,
    note: "Prefer central locations for better access",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    title: "Organize Day Tours in Iceland",
    status: "3",
    cost: 1500,
    duration: 2,
    note: "Include glacier and volcano tours",
    startTime: "12:00",
    endTime: "14:00",
  },
  {
    title: "Confirm Transportation in Oslo",
    status: "2",
    cost: 300,
    duration: 1,
    note: "Check options for rental cars and public transport",
    startTime: "17:00",
    endTime: "18:00",
  },
];
